// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_vexed = "CgkIg8Th9-QIEAIQCg"; // <GPGSID>
        public const string achievement_sidereal = "CgkIg8Th9-QIEAIQCQ"; // <GPGSID>
        public const string achievement_skykinghardworking = "CgkIg8Th9-QIEAIQBw"; // <GPGSID>
        public const string achievement_come_on = "CgkIg8Th9-QIEAIQBg"; // <GPGSID>
        public const string achievement_reach_200_score = "CgkIg8Th9-QIEAIQBQ"; // <GPGSID>
        public const string achievement_reach_100_score = "CgkIg8Th9-QIEAIQBA"; // <GPGSID>
        public const string achievement_reach_25_score = "CgkIg8Th9-QIEAIQAg"; // <GPGSID>
        public const string achievement_all_star = "CgkIg8Th9-QIEAIQCA"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIg8Th9-QIEAIQAQ"; // <GPGSID>
        public const string achievement_reach_50_score = "CgkIg8Th9-QIEAIQAw"; // <GPGSID>

}

